[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200